//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalInventory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
        
        public int EquipmentId { get; set; }
        public string EquipmentName { get; set; }
        public int EquipmentTotalQuantity { get; set; }
        public int EquipmentInUseCount { get; set; }
        public string EquipmentSellerName { get; set; }
        public int EquipmentCategoryId { get; set; }
        public Nullable<int> PatientId { get; set; }
    
        public virtual EquipmentCategory EquipmentCategory { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
